const notes = [
  {
    id: 'note1',
    uid: '12345',
    buildingId: 'building3',
    note: 'Now apartments.',
  },
  {
    id: 'note2',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building1',
    note: 'Now apartments.',
  },
  {
    id: 'note3',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building2',
    note: 'Now apartments.',
  },
  {
    id: 'note4',
    uid: '6789',
    buildingId: 'building4',
    note: 'Now artisan apartments.',
  },
  {
    id: 'note5',
    uid: '12345',
    buildingId: 'builidng5',
    note: 'To be Virgin Hotel.',
  },
  {
    id: 'note6',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'builidng6',
    note: 'To be Virgin Hotel.',
  },
  {
    id: 'note7',
    uid: '6789',
    buildingId: 'builidng7',
    note: 'Is this building record correct?',
  },
  {
    id: 'note8',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building8',
    note: 'Building front says BBR; is this Cedarwood Publishing/Combine?',
  },
  {
    id: 'note9',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building9',
    note: 'not sure if the address 39 Music Square East still exists.',
  },
  {
    id: 'note10',
    uid: '6789',
    buildingId: 'building10',
    note: 'Is now SESAC.',
  },
  {
    id: 'note11',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building11',
    note: 'The closest map view before demolition is 1305 Division St.',
  },
  {
    id: 'note12',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building12',
    note: 'There was a fire here.',
  },
  {
    id: 'note13',
    uid: '6789',
    builidngId: 'building13',
    note: 'Now apartments',
  },
  {
    id: 'note14',
    uid: '12345',
    buildingId: 'building14',
    note: 'Apartments',
  },
  {
    id: 'note15',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building15',
    note: 'apartments',
  },
  {
    id: 'note16',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building16',
    note: 'apartments',
  },
  {
    id: 'note17',
    uid: '12345',
    buildingId: 'building17',
    note: 'apartments',
  },
  {
    id: 'note18',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building18',
    note: 'apartments',
  },
  {
    id: 'note19',
    uid: '12345',
    buildingId: 'building19',
    note: 'parking lot',
  },
  {
    id: 'note20',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building20',
    note: 'mixed use',
  },
  {
    id: 'note21',
    uid: '6789',
    buildingId: 'building21',
    note: 'Sky apartments',
  },
  {
    id: 'note22',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building22',
    note: 'Sky apartments',
  },
  {
    id: 'note23',
    uid: '6789',
    buildingId: 'building23',
    note: 'Sky apartments',
  },
  {
    id: 'note24',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building24',
    note: 'apartments',
  },
  {
    id: 'note25',
    uid: '12345',
    buildingId: 'building25',
    note: 'apartments',
  },
  {
    id: 'note26',
    uid: '12345',
    buildingId: 'building26',
    note: 'apartments',
  },
  {
    id: 'note27',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building27',
    note: 'apartments',
  },
  {
    id: 'note28',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building28',
    note: 'apartments',
  },
  {
    id: 'note29',
    uid: '12345',
    buildingId: 'building29',
    note: 'apartments',
  },
  {
    id: 'note30',
    uid: '6789',
    buildingId: 'building30',
    note: 'apartments',
  },
  {
    id: 'note31',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building31',
    note: 'apartments',
  },
  {
    id: 'note32',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building32',
    note: 'parking lot',
  },
  {
    id: 'note33',
    uid: '6789',
    buildingId: 'building33',
    note: 'office/garage',
  },
  {
    id: 'note34',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building34',
    note: 'office/garage',
  },
  {
    id: 'note35',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building35',
    note: 'office/garage',
  },
  {
    id: 'note36',
    uid: '12345',
    buildingId: 'building36',
    note: 'office (demolished all but three exterior walls',
  },
  {
    id: 'note37',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building37',
    note: 'vacant lot',
  },
  {
    id: 'note38',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building38',
    note: 'apartments',
  },
  {
    id: 'note39',
    uid: '12345',
    buildingId: 'building39',
    note: 'apartments',
  },
  {
    id: 'note40',
    uid: 'qNV6y4IPOxMymlMWsyqagPy2qvv1',
    buildingId: 'building40',
    note: 'apartments',
  },
];

export default notes;
